import type { MetadataRoute } from "next";

/**
 * The web app manifest, and it exists for one specific reason.
 *
 * iPhone Safari has never supported the Fullscreen API on anything but a
 * `<video>`, so the fullscreen button in the touch pad has nothing to call there.
 * Add to Home Screen is the way round it: launched from the home screen with
 * `display: "standalone"`, iOS drops Safari's chrome entirely and Scout gets the
 * whole phone, which is what a landscape game wants.
 *
 * Android gets the same thing, plus a genuine install prompt.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Scout: a pollinator RPG",
    short_name: "Scout",
    description:
      "You are a bee, a centimetre long, in the real parks of Pittsburgh. Every plant is a real species that really grows there.",
    start_url: "/play",
    display: "standalone",
    /**
     * Deliberately NOT `orientation: "landscape"`.
     *
     * Landscape is the right way to play on a phone, and the rotate card asks for
     * it there. But a manifest lock applies to every installed surface, and a
     * tablet held upright is a perfectly good way to play. Locking would have
     * taken that away to solve a problem tablets do not have.
     */
    background_color: "#10140d",
    theme_color: "#3c7d4a",
    categories: ["games", "education"],
    /**
     * The vector first, since it is sharp at whatever size is asked for, then the
     * raster fallbacks for everything that will not take an SVG.
     *
     * `maskable` is a separate file rather than the same one twice, and has to be:
     * a maskable icon can be cropped to a circle, and the bee spans nearly the
     * full width of the mark, so the flat one would lose its wings. That one is
     * padded into the safe zone.
     *
     * iOS is not served from here at all. Safari ignores manifest icons for Add to
     * Home Screen and wants `apple-icon.png`, which App Router picks up from the
     * app directory on its own. All three are generated by `scripts/build-icons.mjs`.
     */
    icons: [
      { src: "/icon.svg", sizes: "any", type: "image/svg+xml", purpose: "any" },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
